# Copyright (c) 2019-2020-2021-2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# Source: https://raw.githubusercontent.com/lukka/CppBuildTasks-Validation/v10/.github/workflows/hosted-ninja-vcpkg_submod-autocache.yml
name: CI
on:
  push: {}
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job:
    permissions:
      actions: read  # vcpkg-cache uses github's action cache, needs only read permission
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows
            preset: windows-release
            # package: windows-release
          - os: ubuntu
            preset: linux-vcpkg
          - os: ubuntu
            preset: linux-release
          - os: macos
            preset: macos-vcpkg

    runs-on: ${{ matrix.os }}-latest
    name: ${{ github.workflow }}-${{ matrix.preset }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          # This is useful to avoid https://github.com/microsoft/vcpkg/issues/25349
          # which is caused by missing Git history on the vcpkg submodule which ports 
          # try to access.
          fetch-depth: 0

      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.31.0"

      - name: List $RUNNER_WORKSPACE before vcpkg is setup
        run: find $RUNNER_WORKSPACE
        shell: bash
      
      - name: Restore cached vcpkg modules # reads from cache here, stores into cache at job end
        id: vcpkg-cache
        if: ${{contains(matrix.preset, 'vcpkg')}}
        uses: TAServers/vcpkg-cache@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} # needs token with action:read permission to read action cache
          prefix: ${{matrix.preset}} # used for cache disambiguation

      - name: Setup vcpkg from scratch # until vcpkg and run-vcpkg fix themselves, we have to use vcpkg-cache with a secret token
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          # This one is not needed, as it is the default value anyway.
          # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "

      - name: Install dependencies on macos
        if: ${{ startsWith(matrix.os, 'macos') }}
        id: macos-deps
        run: brew install sdl

      - name: Install dependencies on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') && !contains(matrix.preset, 'vcpkg') }}
        id: linux-deps
        run: sudo apt-get install libsdl1.2-dev libcereal-dev libphysfs-dev libboost-dev libpng-dev libjsoncpp-dev libogg-dev libvorbis-dev libtheora-dev libprotobuf-dev protobuf-compiler

      - name: Run CMake and CPack # CMake makes exe, CPack makes installer (package)
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: ${{ matrix.preset }}
          buildPreset: ${{ matrix.preset }}
          packagePreset: ${{ matrix.package }}
        env:
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite" # makes CMake aware of vcpkg-cache's cache

      - name: List $RUNNER_WORKSPACE after build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Read output package name
        if: ${{ matrix.package }} # only make installer if we ask for it
        id: readpkg
        shell: bash
        run: |
          PACKAGE_FILE_NAME=$(cat build/release/cpack_output_files.txt)
          echo "Package file name: $PACKAGE_FILE_NAME"
          echo "package_file_name=$PACKAGE_FILE_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload windows binaries artifact # creates temporary archive file with resulting program
        id: upload_artifact
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ github.sha }}
          overwrite: true # keep only one artifact to limit storage requirements
          retention-days: 7
          if-no-files-found: error
          compression-level: 9
          path: |
            build/release/src/game/*.exe
            build/release/src/game/*.dll
            
      - name: Output artifact URL # make download link visible (I hope it's download link?)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          echo "Artifact URL is: ${{ steps.upload_artifact.outputs.artifact-url }}"

      - name: Upload windows installer artifact
        if: ${{ matrix.package }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-latest 
          overwrite: true # keep only one artifact to limit storage requirements
          if-no-files-found: error
          compression-level: 0
          path: ${{ steps.readpkg.outputs.package_file_name }}
